api-gateway:
  port: 8082
  endpoint: tg-updates

logs:
  address: ""  # Empty for console logging only
  level: "info"

metrics:
  enabled: true
  path: "/metrics"
  port: 8082

bot-modules:
  modules:
    anon-chat:
      grpc:
        host: "localhost"
        port: 5002 