apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    uid: DS_PROMETHEUS
    isDefault: true
    editable: false
    version: 1
    jsonData:
      timeInterval: "5s" 