version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    networks:
      - redis_network
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: starsinc
      POSTGRES_PASSWORD: starsinc
      POSTGRES_DB: anon-bot
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network
    ports:
      - "5433:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@postgres.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - postgres_network
    ports:
      - "8091:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:

networks:
  redis_network:
    driver: bridge
  postgres_network:
    driver: bridge