version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    command: redis-api --requirepass secret
    networks:
      - redis_network
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--auth", "secret", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api-gateway
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@postgres.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - postgres_network
    ports:
      - "8091:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:

networks:
  redis_network:
    driver: bridge
  postgres_network:
    driver: bridge